### ISSUE TITLE
How to use it with laravel modules?

### ISSUE THREAD

**Issue by dexcell** [JamesHemery/laravel-json-translation-loader#1]
Hi, i tried your module,
But i didn't managed to make it work, can you help?

I want to load my translation json file from /Modules/MyModule/Resources/lang/

Here is my service provider.
````
public function boot()
    {
       // Auto generated by laravel modules
        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->registerFactories();
        $this->loadMigrationsFrom(module_path('MyModule', 'Database/Migrations'));

        // Load translation from custom directory
        $this->app['translator']->addNamespace('MyModule', module_path('MyModule', 'Resources/lang'));
    }
````
And i have middleware to set the locale
````
// Set locale
App::setLocale($locale);
````
But it doesn't work, the text doesn't get translated.

This works fine if i add the json translation into default resources/lang directory.

Thanks

**Comment by JamesHemery** [comment]
Hi @dexcell,

What is the string you are trying to translate?

When you add a namespace, the one if serves as a prefix. For example if you have a `Modules/MyModule/Resources/lang` file which contains a key `foo.bar,` you must use `@lang ('MyModule::foo.bar ")`

**Comment by dexcell** [comment]
Hi James

Let's say In my controller i have 
````
__('Hello world');
````
I want to translate it using json file, not using short key.

Short key translation already supported out of the box by laravel modules using prefix like you suggest, however apparently it doesn't support  json translation (translation string as keys), which i need.
https://laravel.com/docs/6.x/localization#using-translation-strings-as-keys

**Comment by JamesHemery** [comment]
Okay, that’s not what this package does.  

The problem with doing so is that you might have conflicts between your modules translations.  Unless you develop a system that makes sure to take the translation into the current module.
